### ISSUE TITLE
[bug] you can't click to URL with tip ever

### ISSUE THREAD

**Issue by Kwaskoff** [Switcheo/carbon-js-sdk#232]
![Screenshot from 2022-12-25 22-12-34](https://user-images.githubusercontent.com/15308024/209482109-8f99e2fd-709e-4db0-a8e7-754ee975137f.png)
it hides when I move cursor from (i) to tip =)

**Comment by Kwaskoff** [comment]
page for example https://app.dem.exchange/nitron/withdraw/ibc/75249A18DEFBEFE55F83B1C70CAD234DF164F174C6BC51682EE92C2C81C18C93

**Comment by sarah-thong** [comment]
Hi @Kwaskoff, thanks for reporting this bug! We have since fixed this issue on the application itself.
https://user-images.githubusercontent.com/65583522/226795468-0575ebe3-317e-4d6f-b309-5289dccce3ff.mov

Feel free to [test](https://app.dem.exchange/nitron/withdraw/ibc/75249A18DEFBEFE55F83B1C70CAD234DF164F174C6BC51682EE92C2C81C18C93) it out again.
